= Assurance of Salvation

.https://www.biblegateway.com/passage/?search=Philippians%202%3A12&version=NKJV
[quote,Philippians 2:12,NKJV]
Therefore, my beloved, as you have always obeyed, not as in my presence only, but now much more in my absence, work out your own salvation with fear and trembling;

.https://www.biblegateway.com/passage/?search=2%20Corinthians%2013%3A5&version=NKJV
[quote,2 Corinthians 13:5,NKJV]
Examine yourselves as to whether you are in the faith. Test yourselves. Do you not know yourselves, that Jesus Christ is in you?—unless indeed you are disqualified.


Are you a Christian?  How do you know?  Would you bet your life on it?

== 1 John 1

Scripture:: https://www.blueletterbible.org/nkjv/1jo/1/1/s_1160001
Study Guide:: https://www.blueletterbible.org/comm/guzik_david/study-guide/1-john/1-john-1.cfm

=== Walking in the Light

.https://www.blueletterbible.org/nkjv/1jo/1/7/s_1160007
[quote, 1 John 1:7, NKJV]
But if we walk in the light as He is in the light, we have fellowship with one another, and the blood of Jesus Christ His Son cleanses us from all sin.

 This means to walk in a generally obedient life, without harboring known sin or resisting the conviction of the Holy Spirit on a particular point.

i. John’s message here means that a walk in the light is possible. We know that on this side of eternity, sinless perfection is not possible. Yet we can still walk in the light, so John does mean perfect obedience.

ii. The Christian life is described as walking, which implies activity. Christian life feeds upon contemplation, but it displays itself in action. “Walking” implies action, continuity, and progress. Since God is active and walking, if you have fellowship with Him, you will also be active and walking. 

=== Confession of Sin

== 1 John 2

== OTHER RAW INFO

2. 1 John 1:8-10 (Confession of Sin) 

8 If we say that we have no sin, we deceive ourselves, and the truth is not in us. 9 If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness. 10 If we say that we have not sinned, we make Him a liar, and His word is not in us.

3. 1 John 2:3-4 (Obedience)

3 Now by this we know that we know Him, if we keep His commandments. 4 He who says, "I know Him," and does not keep His commandments, is a liar, and the truth is not in him.

4. 1 John 2:9-11 (Love for the Brethren)

9 He who says he is in the light, and hates his brother, is in darkness until now. 10 He who loves his brother abides in the light, and there is no cause for stumbling in him. 11 But he who hates his brother is in darkness and walks in darkness, and does not know where he is going, because the darkness has blinded his eyes.

5. 1 John 2:15-17 (Hatred for the World) 

15 Do not love the world or the things in the world. If anyone loves the world, the love of the Father is not in him. 16 For all that is in the world--the lust of the flesh, the lust of the eyes, and the pride of life--is not of the Father but is of the world. 17 And the world is passing away, and the lust of it; but he who does the will of God abides forever 

6. 1 John 2:24-25 (Perseverance in Doctrine)

24 Therefore let that abide in you which you heard from the beginning. If what you heard from the beginning abides in you, you also will abide in the Son and in the Father. 25 And this is the promise that He has promised us--eternal life. 

7. 1 John 3:10 (Righteousness)

10 In this the children of God and the children of the devil are manifest: Whoever does not practice righteousness is not of God, nor is he who does not love his brother. 11 For this is the message that you heard from the beginning, that we should love one another,

8. 1 John 4:13 (Spirit's Testimony) 

13 By this we know that we abide in Him, and He in us, because He has given us of His Spirit.

[bibliography]
== Bibliography

* [[[b1]]] Scott Brown. Nine Objective Tests of Salvation from First John. Online. Jul. 28, 2016. https://churchandfamilylife.com/resources/60ca762723fa965169a3c9f0
