= Resisting Temptations

December 12, 2025
1815-1915
SSJS

[quote,evangelists]
sin will take you further than you want to go, keep you longer than you want to stay, and cost you more than you want to pay

.https://www.biblegateway.com/passage/?search=1%20Corinthians%206&version=NKJV
[quote,1 Corinthians 6:9-11;18-20,NKJV]
Do you not know that the unrighteous will not inherit the kingdom of God? Do not be deceived. Neither fornicators, nor idolaters, nor adulterers, nor homosexuals, nor sodomites, nor thieves, nor covetous, nor drunkards, nor revilers, nor extortioners will inherit the kingdom of God. And such were some of you. But you were washed, but you were sanctified, but you were justified in the name of the Lord Jesus and by the Spirit of our God. ... Flee sexual immorality. Every sin that a man does is outside the body, but he who commits sexual immorality sins against his own body. Or do you not know that your body is the temple of the Holy Spirit who is in you, whom you have from God, and you are not your own? For you were bought at a price; therefore glorify God in your body and in your spirit, which are God's.

.https://www.biblegateway.com/passage/?search=1%20thess%204&version=NKJV
[quote,1 Thessalonians 4:3-8,NKJV]
For this is the will of God, your sanctification: that you should abstain from sexual immorality; that each of you should know how to possess his own vessel in sanctification and honor, not in passion of lust, like the Gentiles who do not know God; that no one should take advantage of and defraud his brother in this matter, because the Lord is the avenger of all such, as we also forewarned you and testified. For God did not call us to uncleanness, but in holiness. Therefore he who rejects this does not reject man, but God, who has also given us His Holy Spirit.

.https://www.biblegateway.com/passage/?search=galatians%206%3A7-10&version=NKJV
[quote,Galatians 6:7-10,NKJV]
Do not be deceived, God is not mocked; for whatever a man sows, that he will also reap. For he who sows to his flesh will of the flesh reap corruption, but he who sows to the Spirit will of the Spirit reap everlasting life. And let us not grow weary while doing good, for in due season we shall reap if we do not lose heart.  Therefore, as we have opportunity, let us do good to all, especially to those who are of the household of faith.

.https://www.biblegateway.com/passage/?search=1%20peter%205%3A6-11&version=NKJV
[quote,1 Peter 5:6-11,NKJV]
Therefore humble yourselves under the mighty hand of God, that He may exalt you in due time, casting all your care upon Him, for He cares for you.  Be sober, be vigilant; because your adversary the devil walks about like a roaring lion, seeking whom he may devour. Resist him, steadfast in the faith, knowing that the same sufferings are experienced by your brotherhood in the world. But may the God of all grace, who called us to His eternal glory by Christ Jesus, after you have suffered a while, perfect, establish, strengthen, and settle you. To Him be the glory and the dominion forever and ever. Amen.

== The Holy Spirit

On page 182, in his book _The Holy Spirit_ (<<b1>>), Robert Gromacki says:

[.excerpt]
____
After Paul commanded believers to flee sexual immorality, he reminded them that their bodies were the temples of the indwelling Spirit (1 Cor. 6:18-20).  Our bodies are sacred, sanctified, the very sanctuary of the Spirit, who is holy.  No believer should involve the Spirit in the immoral acts of adultery, fornication, or homosexuality (6:9-11).

Believers should treat the bodies of themselves and others "in sanctification and honor" (1 Thess. 4:4).  In our culture people justify immoral acts with these 
rationalizations:  "We love each other," "We are consenting adults," "No one is getting hurt."  The child of God must reject this kind of nonbiblical logic for one basic reason:  The Holy Spirit is hurt when a Christian violates the proper sexual usage of his body (4:8).  All sin is ultimately against God, and sexual sin by a believer violates the sanctity of the indwelling Spirit.
____

== You are not Alone

.https://www.biblegateway.com/passage/?search=Romans%207%3A15-25&version=NKJV
[quote,Romans 7:15-25,NKJV]
For what I am doing, I do not understand. For what I will to do, that I do not practice; but what I hate, that I do. If, then, I do what I will not to do, I agree with the law that it is good. But now, it is no longer I who do it, but sin that dwells in me. For I know that in me (that is, in my flesh) nothing good dwells; for to will is present with me, but how to perform what is good I do not find. For the good that I will to do, I do not do; but the evil I will not to do, that I practice. Now if I do what I will not to do, it is no longer I who do it, but sin that dwells in me.  I find then a law, that evil is present with me, the one who wills to do good. For I delight in the law of God according to the inward man. But I see another law in my members, warring against the law of my mind, and bringing me into captivity to the law of sin which is in my members. O wretched man that I am! Who will deliver me from this body of death? I thank God—through Jesus Christ our Lord!  So then, with the mind I myself serve the law of God, but with the flesh the law of sin.

.https://www.biblegateway.com/passage/?search=Ps%2032%3A3-4&version=NKJV
[quote,Psalm 32:3-4,NKJV]
When I kept silent, my bones grew old Through my groaning all the day long.  For day and night Your hand was heavy upon me; My vitality was turned into the drought of summer. Selah

== You can receive forgiveness

.https://www.biblegateway.com/passage/?search=Matthew%2011%3A28-30&version=NKJV
[quote,Matthew 11:28-30,NKJV]
Come to Me, all you who labor and are heavy laden, and I will give you rest. Take My yoke upon you and learn from Me, for I am gentle and lowly in heart, and you will find rest for your souls. For My yoke is easy and My burden is light.

.https://www.biblegateway.com/passage/?search=1%20John%201%3A9&version=NKJV
[quote,1 John 1:9,NKJV]
If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.

== What will it cost you

David White in his book _Sexual Sanity for Men_ <<b2>> explains that sexual sin generally leads to escalation, "many end up doing what they previously thought impossible" (page 9).

[.excerpt]
____
This increasing escalation has a price tag.  We all have a very finite life, and yet every day men are sacrificing things of infinite value to pursue their sexual desires.  The time, energy, and money invested in pursuing sexual sin robs from your family, your future security, your carreer aspirations, your ability to serve God and others.  Even our health becomes a casualty.  HIV and other STDs abound.  The strain of living a dobule life results in depression, ulcers, and anxiety.
____

.https://www.biblegateway.com/passage/?search=James%201%3A14-15&version=NKJV
[quote,James 1:14-15,NKJV]
But each one is tempted when he is drawn away by his own desires and enticed. Then, when desire has conceived, it gives birth to sin; and sin, when it is full-grown, brings forth death.

[bibliography]
== Bibliography

* [[[b1]]] Robert Gromacki. The Holy Spirit. World Publishing, 1999, Nashville, Tennessee.  ISBN: 0-8499-1370-5.
* [[[b2]]] David White. Sexual Sanity for Men. New Growth Press, 2012, Greensboro, NC.  ISBN: 978-1-936768-99-8.
