= Resisting Temptations

December 12, 2025
1800
SSJS

.https://www.biblegateway.com/passage/?search=1%20Corinthians%206&version=NKJV
[quote,1 Corinthians 6:9-11;18-20,NKJV]
Do you not know that the unrighteous will not inherit the kingdom of God? Do not be deceived. Neither fornicators, nor idolaters, nor adulterers, nor homosexuals, nor sodomites, nor thieves, nor covetous, nor drunkards, nor revilers, nor extortioners will inherit the kingdom of God. And such were some of you. But you were washed, but you were sanctified, but you were justified in the name of the Lord Jesus and by the Spirit of our God. ... Flee sexual immorality. Every sin that a man does is outside the body, but he who commits sexual immorality sins against his own body. Or do you not know that your body is the temple of the Holy Spirit who is in you, whom you have from God, and you are not your own? For you were bought at a price; therefore glorify God in your body and in your spirit, which are God's.

.https://www.biblegateway.com/passage/?search=1%20thess%204&version=NKJV
[quote,1 Thessalonians 4:3-8,NKJV]
For this is the will of God, your sanctification: that you should abstain from sexual immorality; that each of you should know how to possess his own vessel in sanctification and honor, not in passion of lust, like the Gentiles who do not know God; that no one should take advantage of and defraud his brother in this matter, because the Lord is the avenger of all such, as we also forewarned you and testified. For God did not call us to uncleanness, but in holiness. Therefore he who rejects this does not reject man, but God, who has also given us His Holy Spirit.

== The Holy Spirit

On page 182, in his book _The Holy Spirit_ (<<b1>>), Robert Gromacki says:

[.excerpt]
____

After Paul commanded believers to flee sexual immorality, he reminded them that their bodies were ht etemples of the indwelling Spirit (1 Cor. 6:18-20).  Our bodies are sacred, sanctified, the very sanctuary of the Spirit, who is holy.  No believer should involve the Spirit in the immoral acts of adultery, fornication, or homosexuality (6:9-11).

Believers should treat the bodies of themselves and others "in sanctification and honor" (1 Thess. 4:4).  In our culture people justify immoral acts with thes erationalizations:  "We love each other," "We are consenting adults," "No one is getting hurt."  The child of God must reject this kind of nonbiblical logic for one basic reason:  The Holy Spirit is hurt when a Christian violates the proper sexual usage of his body (4:8).  All sin is ultimately against God, and sexual sin by a believer violates the sanctity of the indwelling Spirit.
____




[bibliography]
== Bibliography

* [[[b1]]] Robert Gromacki. The Holy Spirit. World Publishing, 1999, Nashville, Tennessee.
